// Generated by scripts/generate-design-system.mjs. Do not edit.
// Props/events are extracted from defineProps/defineEmits declarations.
export const componentInventory = [
  {
    "name": "AboutView",
    "file": "components/AboutView.vue",
    "props": [],
    "events": []
  },
  {
    "name": "AgentRunCard",
    "file": "components/AgentRunCard.vue",
    "props": [],
    "events": []
  },
  {
    "name": "AgentsView",
    "file": "components/AgentsView.vue",
    "props": [],
    "events": []
  },
  {
    "name": "ApprovalPrompt",
    "file": "components/ApprovalPrompt.vue",
    "props": [
      {
        "name": "requestId",
        "type": "string"
      },
      {
        "name": "toolName",
        "type": "string"
      },
      {
        "name": "input",
        "type": "Record<string, unknown>"
      },
      {
        "name": "description",
        "type": "string | undefined"
      },
      {
        "name": "context",
        "type": "string | undefined"
      }
    ],
    "events": [
      {
        "name": "respond",
        "payload": "requestId: string, approved: boolean"
      }
    ]
  },
  {
    "name": "ArtifactFrame",
    "file": "components/ArtifactFrame.vue",
    "props": [
      {
        "name": "content",
        "type": "string"
      },
      {
        "name": "title",
        "type": "string | undefined"
      },
      {
        "name": "layout",
        "type": "'normal' | 'wide' | 'full' | undefined"
      },
      {
        "name": "chrome",
        "type": "'default' | 'none' | undefined"
      },
      {
        "name": "streaming",
        "type": "boolean | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "BondButton",
    "file": "components/BondButton.vue",
    "props": [
      {
        "name": "variant",
        "type": "'primary' | 'secondary' | 'ghost' | 'danger' | undefined"
      },
      {
        "name": "size",
        "type": "'sm' | 'md' | undefined"
      },
      {
        "name": "icon",
        "type": "boolean | undefined"
      },
      {
        "name": "disabled",
        "type": "boolean | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "BondFlyoutMenu",
    "file": "components/BondFlyoutMenu.vue",
    "props": [
      {
        "name": "open",
        "type": "boolean"
      },
      {
        "name": "anchor",
        "type": "HTMLElement | null"
      },
      {
        "name": "placement",
        "type": "'bottom-start' | 'bottom-end' | 'top-start' | 'top-end' | undefined"
      },
      {
        "name": "width",
        "type": "number | undefined"
      },
      {
        "name": "padding",
        "type": "boolean | undefined"
      }
    ],
    "events": [
      {
        "name": "close",
        "payload": "void"
      }
    ]
  },
  {
    "name": "BondInput",
    "file": "components/BondInput.vue",
    "props": [
      {
        "name": "modelValue",
        "type": "string | undefined"
      },
      {
        "name": "placeholder",
        "type": "string | undefined"
      },
      {
        "name": "disabled",
        "type": "boolean | undefined"
      },
      {
        "name": "type",
        "type": "string | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "BondPanel",
    "file": "components/BondPanel.vue",
    "props": [
      {
        "name": "id",
        "type": "string"
      },
      {
        "name": "defaultSize",
        "type": "number | undefined"
      },
      {
        "name": "minSize",
        "type": "number | undefined"
      },
      {
        "name": "maxSize",
        "type": "number | undefined"
      },
      {
        "name": "minSizePx",
        "type": "number | undefined"
      },
      {
        "name": "unit",
        "type": "PanelUnit | undefined"
      },
      {
        "name": "collapsible",
        "type": "boolean | undefined"
      },
      {
        "name": "collapsedSize",
        "type": "number | undefined"
      },
      {
        "name": "header",
        "type": "string | undefined"
      },
      {
        "name": "startCollapsed",
        "type": "boolean | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "BondPanelGroup",
    "file": "components/BondPanelGroup.vue",
    "props": [
      {
        "name": "direction",
        "type": "PanelDirection | undefined"
      },
      {
        "name": "autoSaveId",
        "type": "string | undefined"
      },
      {
        "name": "keyboardStep",
        "type": "number | undefined"
      }
    ],
    "events": [
      {
        "name": "layoutChange",
        "payload": "layout: Record<string, number>"
      },
      {
        "name": "layoutChanged",
        "payload": "layout: Record<string, number>"
      }
    ]
  },
  {
    "name": "BondPanelHandle",
    "file": "components/BondPanelHandle.vue",
    "props": [
      {
        "name": "id",
        "type": "string"
      },
      {
        "name": "beforePanelId",
        "type": "string"
      },
      {
        "name": "afterPanelId",
        "type": "string"
      },
      {
        "name": "disabled",
        "type": "boolean | undefined"
      },
      {
        "name": "hitArea",
        "type": "number | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "BondSelect",
    "file": "components/BondSelect.vue",
    "props": [
      {
        "name": "modelValue",
        "type": "string | undefined"
      },
      {
        "name": "disabled",
        "type": "boolean | undefined"
      },
      {
        "name": "placement",
        "type": "'top' | 'bottom' | undefined"
      },
      {
        "name": "variant",
        "type": "'default' | 'minimal' | undefined"
      },
      {
        "name": "size",
        "type": "'sm' | 'md' | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "BondTab",
    "file": "components/BondTab.vue",
    "props": [
      {
        "name": "modelValue",
        "type": "string | undefined"
      },
      {
        "name": "size",
        "type": "'sm' | 'md' | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "BondText",
    "file": "components/BondText.vue",
    "props": [
      {
        "name": "as",
        "type": "string | undefined"
      },
      {
        "name": "size",
        "type": "'xs' | 'sm' | 'base' | 'lg' | 'xl' | '2xl' | '3xl' | undefined"
      },
      {
        "name": "weight",
        "type": "'normal' | 'medium' | 'semibold' | 'bold' | undefined"
      },
      {
        "name": "color",
        "type": "'primary' | 'muted' | 'accent' | 'err' | 'ok' | 'inherit' | undefined"
      },
      {
        "name": "align",
        "type": "'left' | 'center' | 'right' | undefined"
      },
      {
        "name": "truncate",
        "type": "boolean | undefined"
      },
      {
        "name": "mono",
        "type": "boolean | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "BondTextarea",
    "file": "components/BondTextarea.vue",
    "props": [
      {
        "name": "modelValue",
        "type": "string | undefined"
      },
      {
        "name": "placeholder",
        "type": "string | undefined"
      },
      {
        "name": "disabled",
        "type": "boolean | undefined"
      },
      {
        "name": "rows",
        "type": "number | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "BondToolbar",
    "file": "components/BondToolbar.vue",
    "props": [
      {
        "name": "label",
        "type": "string"
      },
      {
        "name": "border",
        "type": "'none' | 'bottom' | undefined"
      },
      {
        "name": "drag",
        "type": "boolean | undefined"
      },
      {
        "name": "blur",
        "type": "boolean | undefined"
      },
      {
        "name": "insetStart",
        "type": "boolean | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "ChatInput",
    "file": "components/ChatInput.vue",
    "props": [
      {
        "name": "busy",
        "type": "boolean"
      },
      {
        "name": "model",
        "type": "ModelId"
      },
      {
        "name": "editMode",
        "type": "EditMode"
      },
      {
        "name": "placeholder",
        "type": "string | undefined"
      },
      {
        "name": "mobile",
        "type": "boolean | undefined"
      }
    ],
    "events": [
      {
        "name": "submit",
        "payload": "text: string, images: AttachedImage["
      },
      {
        "name": "cancel",
        "payload": "void"
      }
    ]
  },
  {
    "name": "CollectionDetail",
    "file": "components/CollectionDetail.vue",
    "props": [
      {
        "name": "collection",
        "type": "Collection"
      }
    ],
    "events": []
  },
  {
    "name": "CollectionItemDetail",
    "file": "components/CollectionItemDetail.vue",
    "props": [
      {
        "name": "collection",
        "type": "Collection"
      },
      {
        "name": "itemId",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "back",
        "payload": "void"
      },
      {
        "name": "deleted",
        "payload": "void"
      }
    ]
  },
  {
    "name": "CollectionsView",
    "file": "components/CollectionsView.vue",
    "props": [
      {
        "name": "collections",
        "type": "Collection[]"
      },
      {
        "name": "archivedCollections",
        "type": "Collection[]"
      },
      {
        "name": "activeCollectionId",
        "type": "string | null"
      }
    ],
    "events": [
      {
        "name": "select",
        "payload": "id: string"
      },
      {
        "name": "archive",
        "payload": "id: string"
      },
      {
        "name": "unarchive",
        "payload": "id: string"
      },
      {
        "name": "remove",
        "payload": "id: string"
      },
      {
        "name": "back",
        "payload": "void"
      }
    ]
  },
  {
    "name": "ContextGauge",
    "file": "components/ContextGauge.vue",
    "props": [
      {
        "name": "used",
        "type": "number"
      },
      {
        "name": "limit",
        "type": "number"
      },
      {
        "name": "cost",
        "type": "number | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "CopyButton",
    "file": "components/CopyButton.vue",
    "props": [
      {
        "name": "value",
        "type": "string"
      }
    ],
    "events": []
  },
  {
    "name": "DesignSystemView",
    "file": "components/DesignSystemView.vue",
    "props": [],
    "events": []
  },
  {
    "name": "DeskInFlight",
    "file": "components/DeskInFlight.vue",
    "props": [
      {
        "name": "blocks",
        "type": "DeskBlockDetail[]"
      },
      {
        "name": "threads",
        "type": "DeskThread[]"
      },
      {
        "name": "isDark",
        "type": "boolean | undefined"
      },
      {
        "name": "reassigning",
        "type": "string | null | undefined"
      },
      {
        "name": "busy",
        "type": "boolean | undefined"
      }
    ],
    "events": [
      {
        "name": "reassign",
        "payload": "blockId: string, threadId: string"
      },
      {
        "name": "openPicker",
        "payload": "blockId: string | null"
      }
    ]
  },
  {
    "name": "DeskToday",
    "file": "components/DeskToday.vue",
    "props": [
      {
        "name": "items",
        "type": "TodayItem[]"
      },
      {
        "name": "busy",
        "type": "boolean | undefined"
      }
    ],
    "events": [
      {
        "name": "toggle",
        "payload": "itemId: string, done: boolean"
      },
      {
        "name": "add",
        "payload": "title: string"
      }
    ]
  },
  {
    "name": "DeskView",
    "file": "components/DeskView.vue",
    "props": [],
    "events": []
  },
  {
    "name": "DevComponents",
    "file": "components/DevComponents.vue",
    "props": [],
    "events": []
  },
  {
    "name": "EmbedRenderer",
    "file": "components/EmbedRenderer.vue",
    "props": [
      {
        "name": "embedType",
        "type": "string"
      },
      {
        "name": "attrs",
        "type": "Record<string, string>"
      }
    ],
    "events": []
  },
  {
    "name": "CollectionEmbed",
    "file": "components/embeds/CollectionEmbed.vue",
    "props": [
      {
        "name": "name",
        "type": "string | undefined"
      },
      {
        "name": "filter",
        "type": "string       // \"field=value\" | undefined"
      },
      {
        "name": "search",
        "type": "string       // text search across primary field | undefined"
      },
      {
        "name": "ids",
        "type": "string          // comma-separated item IDs | undefined"
      },
      {
        "name": "limit",
        "type": "string        // max items | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "MediaEmbed",
    "file": "components/embeds/MediaEmbed.vue",
    "props": [
      {
        "name": "ids",
        "type": "string        // comma-separated image IDs — show specific images | undefined"
      },
      {
        "name": "search",
        "type": "string     // filter by filename | undefined"
      },
      {
        "name": "limit",
        "type": "string | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "SoulEmbed",
    "file": "components/embeds/SoulEmbed.vue",
    "props": [],
    "events": []
  },
  {
    "name": "FieldManual",
    "file": "components/FieldManual.vue",
    "props": [
      {
        "name": "open",
        "type": "boolean"
      }
    ],
    "events": [
      {
        "name": "close",
        "payload": "void"
      }
    ]
  },
  {
    "name": "FieldEditor",
    "file": "components/fields/FieldEditor.vue",
    "props": [
      {
        "name": "def",
        "type": "FieldDef"
      },
      {
        "name": "modelValue",
        "type": "unknown"
      }
    ],
    "events": []
  },
  {
    "name": "FieldValue",
    "file": "components/fields/FieldValue.vue",
    "props": [
      {
        "name": "value",
        "type": "unknown"
      },
      {
        "name": "def",
        "type": "FieldDef"
      }
    ],
    "events": []
  },
  {
    "name": "LibraryView",
    "file": "components/LibraryView.vue",
    "props": [],
    "events": []
  },
  {
    "name": "MarkdownMessage",
    "file": "components/MarkdownMessage.vue",
    "props": [],
    "events": []
  },
  {
    "name": "MarkdownViewer",
    "file": "components/MarkdownViewer.vue",
    "props": [
      {
        "name": "filePath",
        "type": "string"
      }
    ],
    "events": []
  },
  {
    "name": "McpSettings",
    "file": "components/McpSettings.vue",
    "props": [],
    "events": []
  },
  {
    "name": "MemoryView",
    "file": "components/MemoryView.vue",
    "props": [],
    "events": []
  },
  {
    "name": "MessageBubble",
    "file": "components/MessageBubble.vue",
    "props": [
      {
        "name": "msg",
        "type": "Message"
      },
      {
        "name": "id",
        "type": "string | undefined"
      },
      {
        "name": "threadsEnabled",
        "type": "boolean | undefined"
      }
    ],
    "events": [
      {
        "name": "approve",
        "payload": "requestId: string, approved: boolean"
      },
      {
        "name": "openActivity",
        "payload": "void"
      },
      {
        "name": "openThread",
        "payload": "messageId: string"
      }
    ]
  },
  {
    "name": "MissionBriefing",
    "file": "components/MissionBriefing.vue",
    "props": [],
    "events": []
  },
  {
    "name": "QuestionPrompt",
    "file": "components/QuestionPrompt.vue",
    "props": [
      {
        "name": "questionId",
        "type": "string"
      },
      {
        "name": "question",
        "type": "string"
      },
      {
        "name": "header",
        "type": "string | undefined"
      },
      {
        "name": "options",
        "type": "QuestionOption[]"
      }
    ],
    "events": [
      {
        "name": "answer",
        "payload": "questionId: string, answer: QuestionAnswer"
      }
    ]
  },
  {
    "name": "SenseAppLegend",
    "file": "components/SenseAppLegend.vue",
    "props": [
      {
        "name": "apps",
        "type": "AppSummary[]"
      },
      {
        "name": "activeFilter",
        "type": "string | null"
      }
    ],
    "events": [
      {
        "name": "filter",
        "payload": "bundleId: string"
      }
    ]
  },
  {
    "name": "SenseDayNav",
    "file": "components/SenseDayNav.vue",
    "props": [
      {
        "name": "date",
        "type": "string"
      },
      {
        "name": "isToday",
        "type": "boolean"
      },
      {
        "name": "captureCount",
        "type": "number"
      },
      {
        "name": "sessionCount",
        "type": "number"
      }
    ],
    "events": [
      {
        "name": "prev",
        "payload": "void"
      },
      {
        "name": "next",
        "payload": "void"
      },
      {
        "name": "pick",
        "payload": "date: string"
      }
    ]
  },
  {
    "name": "SenseDetail",
    "file": "components/SenseDetail.vue",
    "props": [
      {
        "name": "capture",
        "type": "SenseCapture | null"
      },
      {
        "name": "image",
        "type": "string | null"
      },
      {
        "name": "loadingImage",
        "type": "boolean"
      }
    ],
    "events": []
  },
  {
    "name": "SensePanelView",
    "file": "components/SensePanelView.vue",
    "props": [],
    "events": []
  },
  {
    "name": "SenseSearch",
    "file": "components/SenseSearch.vue",
    "props": [
      {
        "name": "results",
        "type": "SenseCapture[]"
      },
      {
        "name": "query",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "search",
        "payload": "query: string"
      },
      {
        "name": "select",
        "payload": "capture: SenseCapture"
      },
      {
        "name": "clear",
        "payload": "void"
      }
    ]
  },
  {
    "name": "SenseTimeline",
    "file": "components/SenseTimeline.vue",
    "props": [
      {
        "name": "captures",
        "type": "SenseCapture[]"
      },
      {
        "name": "sessions",
        "type": "SenseSession[]"
      },
      {
        "name": "activeCaptureId",
        "type": "string | null"
      },
      {
        "name": "appFilter",
        "type": "string | null"
      }
    ],
    "events": [
      {
        "name": "select",
        "payload": "id: string"
      },
      {
        "name": "preview",
        "payload": "id: string"
      },
      {
        "name": "preview-clear",
        "payload": "void"
      }
    ]
  },
  {
    "name": "SenseView",
    "file": "components/SenseView.vue",
    "props": [
      {
        "name": "insetStart",
        "type": "boolean | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "SettingsView",
    "file": "components/SettingsView.vue",
    "props": [],
    "events": [
      {
        "name": "createSkill",
        "payload": "description: string"
      }
    ]
  },
  {
    "name": "TasksView",
    "file": "components/TasksView.vue",
    "props": [
      {
        "name": "focusRunId",
        "type": "string | null | undefined"
      }
    ],
    "events": []
  },
  {
    "name": "ThinkingIndicator",
    "file": "components/ThinkingIndicator.vue",
    "props": [],
    "events": []
  },
  {
    "name": "ThreadPanel",
    "file": "components/ThreadPanel.vue",
    "props": [
      {
        "name": "threadId",
        "type": "string"
      },
      {
        "name": "model",
        "type": "ModelId"
      },
      {
        "name": "autoFocus",
        "type": "boolean | undefined"
      }
    ],
    "events": [
      {
        "name": "close",
        "payload": "void"
      },
      {
        "name": "summarySent",
        "payload": "void"
      }
    ]
  },
  {
    "name": "ThreadsView",
    "file": "components/ThreadsView.vue",
    "props": [],
    "events": [
      {
        "name": "open",
        "payload": "threadId: string"
      }
    ]
  },
  {
    "name": "TurnActivity",
    "file": "components/TurnActivity.vue",
    "props": [
      {
        "name": "data",
        "type": "TurnActivityData"
      }
    ],
    "events": [
      {
        "name": "approve",
        "payload": "requestId: string, approved: boolean"
      }
    ]
  },
  {
    "name": "ViewShell",
    "file": "components/ViewShell.vue",
    "props": [
      {
        "name": "title",
        "type": "string"
      },
      {
        "name": "insetStart",
        "type": "boolean | undefined"
      },
      {
        "name": "titleEditable",
        "type": "boolean | undefined"
      }
    ],
    "events": [
      {
        "name": "rename",
        "payload": "title: string"
      }
    ]
  }
] as const
