// Generated by scripts/generate-design-system.mjs. Do not edit.
export const componentInventory = [
  {
    "name": "AboutView",
    "file": "components/AboutView.vue"
  },
  {
    "name": "ApprovalPrompt",
    "file": "components/ApprovalPrompt.vue"
  },
  {
    "name": "ArtifactFrame",
    "file": "components/ArtifactFrame.vue"
  },
  {
    "name": "BondButton",
    "file": "components/BondButton.vue"
  },
  {
    "name": "BondFlyoutMenu",
    "file": "components/BondFlyoutMenu.vue"
  },
  {
    "name": "BondInput",
    "file": "components/BondInput.vue"
  },
  {
    "name": "BondPanel",
    "file": "components/BondPanel.vue"
  },
  {
    "name": "BondPanelGroup",
    "file": "components/BondPanelGroup.vue"
  },
  {
    "name": "BondPanelHandle",
    "file": "components/BondPanelHandle.vue"
  },
  {
    "name": "BondSelect",
    "file": "components/BondSelect.vue"
  },
  {
    "name": "BondTab",
    "file": "components/BondTab.vue"
  },
  {
    "name": "BondText",
    "file": "components/BondText.vue"
  },
  {
    "name": "BondTextarea",
    "file": "components/BondTextarea.vue"
  },
  {
    "name": "BondToolbar",
    "file": "components/BondToolbar.vue"
  },
  {
    "name": "ChatInput",
    "file": "components/ChatInput.vue"
  },
  {
    "name": "CollectionDetail",
    "file": "components/CollectionDetail.vue"
  },
  {
    "name": "CollectionItemDetail",
    "file": "components/CollectionItemDetail.vue"
  },
  {
    "name": "CollectionsView",
    "file": "components/CollectionsView.vue"
  },
  {
    "name": "ContextGauge",
    "file": "components/ContextGauge.vue"
  },
  {
    "name": "CopyButton",
    "file": "components/CopyButton.vue"
  },
  {
    "name": "DesignSystemView",
    "file": "components/DesignSystemView.vue"
  },
  {
    "name": "DevComponents",
    "file": "components/DevComponents.vue"
  },
  {
    "name": "EmbedRenderer",
    "file": "components/EmbedRenderer.vue"
  },
  {
    "name": "CollectionEmbed",
    "file": "components/embeds/CollectionEmbed.vue"
  },
  {
    "name": "MediaEmbed",
    "file": "components/embeds/MediaEmbed.vue"
  },
  {
    "name": "SoulEmbed",
    "file": "components/embeds/SoulEmbed.vue"
  },
  {
    "name": "FieldManual",
    "file": "components/FieldManual.vue"
  },
  {
    "name": "FieldEditor",
    "file": "components/fields/FieldEditor.vue"
  },
  {
    "name": "FieldValue",
    "file": "components/fields/FieldValue.vue"
  },
  {
    "name": "MarkdownMessage",
    "file": "components/MarkdownMessage.vue"
  },
  {
    "name": "MarkdownViewer",
    "file": "components/MarkdownViewer.vue"
  },
  {
    "name": "MediaView",
    "file": "components/MediaView.vue"
  },
  {
    "name": "MemoryView",
    "file": "components/MemoryView.vue"
  },
  {
    "name": "MessageBubble",
    "file": "components/MessageBubble.vue"
  },
  {
    "name": "MissionBriefing",
    "file": "components/MissionBriefing.vue"
  },
  {
    "name": "QuickChat",
    "file": "components/QuickChat.vue"
  },
  {
    "name": "SenseAppLegend",
    "file": "components/SenseAppLegend.vue"
  },
  {
    "name": "SenseDayNav",
    "file": "components/SenseDayNav.vue"
  },
  {
    "name": "SenseDetail",
    "file": "components/SenseDetail.vue"
  },
  {
    "name": "SensePanelView",
    "file": "components/SensePanelView.vue"
  },
  {
    "name": "SenseSearch",
    "file": "components/SenseSearch.vue"
  },
  {
    "name": "SenseTimeline",
    "file": "components/SenseTimeline.vue"
  },
  {
    "name": "SenseView",
    "file": "components/SenseView.vue"
  },
  {
    "name": "SettingsView",
    "file": "components/SettingsView.vue"
  },
  {
    "name": "ThinkingIndicator",
    "file": "components/ThinkingIndicator.vue"
  },
  {
    "name": "TurnActivity",
    "file": "components/TurnActivity.vue"
  },
  {
    "name": "ViewShell",
    "file": "components/ViewShell.vue"
  }
] as const
